/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155111: {
    MockAave: {
      address: "0xe13bDfFa500c9be38fF4954Dac94e5eB412C6079",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Deposited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdrawn",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "deposit",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "deposits",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalDeposits",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9976279,
    },
    MockCompound: {
      address: "0x410b3776A0e4a2d7F322d06EaBd7448875B98dc4",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Deposited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdrawn",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "deposit",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "deposits",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalDeposits",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9976280,
    },
    MockUniswap: {
      address: "0xcB5899B48E9c052c02Df0a5E5117E945a2c03fCf",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Deposited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdrawn",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "deposit",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "deposits",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalDeposits",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9976281,
    },
    PermiSIPAI: {
      address: "0xb62C526E8bE91923C8fFBa208908125e59712D73",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_aave",
              type: "address",
            },
            {
              internalType: "address",
              name: "_compound",
              type: "address",
            },
            {
              internalType: "address",
              name: "_uniswap",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "AgentPaymentExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "DepositExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "oldAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newAddress",
              type: "address",
            },
          ],
          name: "ExpertAgentAddressUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "protocol",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "FundsAllocated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "duration",
              type: "uint256",
            },
          ],
          name: "LegacySIPCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
          ],
          name: "PlanCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
          ],
          name: "PlanPaused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "aavePercent",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "compoundPercent",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "uniswapPercent",
              type: "uint8",
            },
          ],
          name: "PlanRebalanced",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
          ],
          name: "PlanResumed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "monthlyAmount",
              type: "uint256",
            },
          ],
          name: "SIPCreated",
          type: "event",
        },
        {
          inputs: [],
          name: "NATIVE_ETH",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "USDC",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "aave",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "cancelPlan",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
          ],
          name: "cancelPlanById",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "compound",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "monthlyAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "duration",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "aavePercent",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "compoundPercent",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "uniswapPercent",
              type: "uint8",
            },
          ],
          name: "createSIPPlan",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "monthlyAmount",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "aavePercent",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "compoundPercent",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "uniswapPercent",
              type: "uint8",
            },
            {
              internalType: "bool",
              name: "enableRebalancing",
              type: "bool",
            },
          ],
          name: "createSIPPlanWithId",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
          ],
          name: "depositForUser",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
          ],
          name: "depositToPlan",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "expertAgentAddress",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getPlan",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "planId",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "monthlyAmount",
                  type: "uint256",
                },
                {
                  components: [
                    {
                      internalType: "uint8",
                      name: "aavePercent",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "compoundPercent",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "uniswapPercent",
                      type: "uint8",
                    },
                  ],
                  internalType: "struct PermiSIPAI.Strategy",
                  name: "strategy",
                  type: "tuple",
                },
                {
                  internalType: "uint256",
                  name: "totalDeposited",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lastDepositTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "rebalancingEnabled",
                  type: "bool",
                },
              ],
              internalType: "struct PermiSIPAI.SIPPlan",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
          ],
          name: "getPlanById",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "planId",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "monthlyAmount",
                  type: "uint256",
                },
                {
                  components: [
                    {
                      internalType: "uint8",
                      name: "aavePercent",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "compoundPercent",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "uniswapPercent",
                      type: "uint8",
                    },
                  ],
                  internalType: "struct PermiSIPAI.Strategy",
                  name: "strategy",
                  type: "tuple",
                },
                {
                  internalType: "uint256",
                  name: "totalDeposited",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lastDepositTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "rebalancingEnabled",
                  type: "bool",
                },
              ],
              internalType: "struct PermiSIPAI.SIPPlan",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getUserPlanIds",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "legacyUserPlans",
          outputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "monthlyAmount",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "uint8",
                  name: "aavePercent",
                  type: "uint8",
                },
                {
                  internalType: "uint8",
                  name: "compoundPercent",
                  type: "uint8",
                },
                {
                  internalType: "uint8",
                  name: "uniswapPercent",
                  type: "uint8",
                },
              ],
              internalType: "struct PermiSIPAI.Strategy",
              name: "strategy",
              type: "tuple",
            },
            {
              internalType: "uint256",
              name: "totalDeposited",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastDepositTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "rebalancingEnabled",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pausePlan",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
          ],
          name: "pausePlanById",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "newAavePercent",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "newCompoundPercent",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "newUniswapPercent",
              type: "uint8",
            },
          ],
          name: "rebalance",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "resumePlan",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
          ],
          name: "resumePlanById",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_expertAgentAddress",
              type: "address",
            },
          ],
          name: "setExpertAgentAddress",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "enabled",
              type: "bool",
            },
          ],
          name: "setRebalancing",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "uniswap",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "userPlanIds",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "userPlans",
          outputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "planId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "monthlyAmount",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "uint8",
                  name: "aavePercent",
                  type: "uint8",
                },
                {
                  internalType: "uint8",
                  name: "compoundPercent",
                  type: "uint8",
                },
                {
                  internalType: "uint8",
                  name: "uniswapPercent",
                  type: "uint8",
                },
              ],
              internalType: "struct PermiSIPAI.Strategy",
              name: "strategy",
              type: "tuple",
            },
            {
              internalType: "uint256",
              name: "totalDeposited",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastDepositTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "rebalancingEnabled",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9976835,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
